imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\Usuario

easy_admin:
    site_name: 'Club de rob&oacute;tica'
    formats:
      date: 'd/m/Y'
    design:
      color_scheme: 'dark'
      brand_color: '#f44336'
      form_theme: 'horizontal'
    list:
        max_results: 10
        actions:
            - { name: 'show', label: '', icon: 'search'}
            - { name: 'edit', label: '', icon: 'pencil' }
            - { name: '-delete', label: '', icon: '' }
            - { name: 'search', label: 'Búsqueda' }
    show:
        actions:
            - { name: 'edit', label: 'Actualizar' }
            - { name: 'list', label: 'Regresar al menu' }
    edit:
        actions:
            - { name: 'list', label: 'Regresar al menú' }
    new:
        actions:
            - { name: 'list', label: 'Regresar al menú' }       
    entities:
        Alumno:
            label: 'Alumnos'
            class: AppBundle\Entity\Alumno
            list:
                title: "Alumnos"
                actions: [{ name: 'new', label: 'Agregar Alumno' }]
                fields: ['id', 'nombre', 'apellido_paterno', 'apellido_materno', { property: 'correo_electronico', type: 'email', label: 'Correo electr&oacute;nico' }]
        Asesor:
            label: 'Asesores'
            class: AppBundle\Entity\Asesor
            list:
                title: "Asesores"
                actions: [{ name: 'new', label: 'Agregar Asesor' }]
                fields: ['id', 'nombre', 'correo_electronico', { property: 'correo_electronico', type: 'email', label: 'Correo electr&oacute;nico' }]
        Carrera:
            label: 'Carreras'
            class: AppBundle\Entity\Carrera
            list:
                title: "Carreras"
                actions: [{ name: 'new', label: 'Agregar Carrera' }]
                fields: ['id', 'nombre']                
        Integrante:
            label: 'Equipos'
            class: AppBundle\Entity\Integrante
            list:
                title: "Equipos"
                actions: [{ name: 'new', label: 'Agregar Integrante' }]
                fields: ['id', 'alumno', { property: 'capitan', type: 'boolean', label: 'Capit&aacute;n' }, { property: 'equipo', label: 'Robot' }, { property: 'equipo.asesor', label: 'Asesor' }]
        Robot:
            label: 'Robots'
            class: AppBundle\Entity\Robot
            list:
                title: "Robots"
                actions: [{ name: 'new', label: 'Agregar Robot' }]
        Usuario:
            class: AppBundle\Entity\Usuario
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin